### ISSUE TITLE
server listening & webrtc

### ISSUE THREAD

**Issue by mcff2** [cea-sec/sanzu#124]
Hi, thank you very much for this work, which is really usefull (and awaited for a pretty long time!).

I have a couple of questions:
- when the client quits, the server quits also. Does an option exist so that the server falls back to a listening state when the client exits?
- I watched the interesting STICC22 presentation :-) : if you could share even a very preliminar version of the webrtc features, I would be very interessted...

All the best & happy new year!

**Comment by serpilliere** [comment]
Hi @mcff2, and thank you for the feedback!

Your first remark is interesting:
We had in mind that the `sanzu_client/sanzu_server` are basic point to point remote graphic, and that if the user wants "advanced" connection management, he uses the `sanzu_broker`. But I agree with you, the "loop" feature is indeed interesting anyway (and is not really an advance feature) in the `sanzu_server`. So I will have a try adding this feature.

For the second question, the webrtc was a quick & dirty hack based on the very first version of sanzu, which event doesn't compile with the current branch. I am currently making an 'async' version of sanzu, reducing the latency. Once this job is done, I will update the webrtc version on this branch to avoid doing the job twice.

**Comment by serpilliere** [comment]
You now have the "--loop" which adds the loop feature
