### ISSUE TITLE
Verbosity of sanzu's windows binaries

### ISSUE THREAD

**Issue by mcff2** [cea-sec/sanzu#133]
My windows sanzu binaries are not verbose at all: they do not output anything on the console (no error, no warning, nothing). Even the help message is not printed on the console.

Is it the normal behavior on windows?

**Comment by serpilliere** [comment]
Ok, after some documentation reading, a call to `AttachConsole` seems to do the trick: With a sanzu compiled as GUI application, the console output seems to be honored.
The PR #134  should to the trick.

**Comment by serpilliere** [comment]
The PR merge automatically closes the issue, but fell free to reopen it / comment it if something goes wrong regarding the fix!
