### ISSUE TITLE
Problem to launch the demo

### ISSUE THREAD

**Issue by iziels** [cea-sec/sanzu#187]
Hello,

I come to you, because I have a problem to launch the demo.

Here are the details of the actions:
I test on an Ubuntu 22.04.
I have installed git, docker and xvfb.

I launch well in a terminal `Xvfb :100`
In another terminal I do: `./run-demo.sh -l`

It returns me the command to execute for the client.
I execute this command in another terminal, the command returned by the server is to be modified it is necessary to replace the _ by -.
Once the command is launched nothing happens, I have no browser that opens.

Thanks in advance,

**Comment by serpilliere** [comment]
Hi @iziels !
You are right: I forgot to update the demo scripts after the command line update.
I will fix this and see what's going for the firefox
Thank you

**Comment by iziels** [comment]
Hi @serpilliere 
Thank you for your feedback

**Comment by serpilliere** [comment]
Hi @serpilliere 
I made #188 which should solve the issue.
For the demo, you must not run Xvfb;
The steps are:
- on the host, (which has a running X server) run `./run-demo.sh -l`
- on the host, run the command given by the previous line
I retested it here.

Moreover, you can only execute:
- on the host, run `./run-demo.sh`
This runs the sanzu server and the client server and display it on your local X server.

**Comment by serpilliere** [comment]
The PR merge has closed the issue @iziels , but feel free to re open it if you have any trouble running the demo
