### ISSUE TITLE
Xvfb cannot support multi successive sessions ?

### ISSUE THREAD

**Issue by mcff2** [cea-sec/sanzu#197]
Well, it's certainly not a sanzu issue, but if you have any clue...

The first time I connect to sanzu_server, everything works well (ie sanzu does its job, I can work, etc.)

Then I quit sanzu, and try to reconnect, and patatra, It doesn't work.

The sanzu_server says "cannot  init_x11rb". The only solution  I found is to kill and restart Xvfb, but I obviously lose all the env...

Do you have any clue on that ?

Thanks !

**Comment by serpilliere** [comment]
Hi @mcff2 !
It's a bit hard to troubleshoot with little information, but maybe you can:
- be sure to run Xvfb using a resolution bigger than the client biggest resolution (for example 4096*4096)
- re run the server using verbose to get better error logging (using -vvv)
- be sure between the two run that xvfb is still alive, and the DISPLAY environment variable is still on your sanzu server command line
- are you using the "--keep-listening" on the server side or do you run another server? I suspect a possible but in this option.
Moreover, can you provide a bit more information on your setup? 
(Client/server option, if you use sanzu broker, client os)

**Comment by mcff2** [comment]
Hello,

it looks the culprit was that I ran Xvfb with a too low resolution. As suggested, running in a higher resolution fixed this issue.

Thanks !
